# Generated by Django 3.1.7 on 2021-03-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20210319_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=100)),
                ('stream', models.CharField(default='', max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='superadmin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
